// Generated by CoffeeScript 1.7.1
$(function() {
  var image_canvas, objFile;
  NCMB.initialize("APPLICATION_KEY", "CLIENT_KEY");
  objFile = new NCMB.File("app-67760_640.jpg", null, null, null);
  image_canvas = document.getElementById("image_canvas");
  return objFile.fetchImgSource(image_canvas);
});
